// models/ApplicationFileFile.js
import mongoose from 'mongoose';

const ApplicationFileSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, default: "Untitled" },
  vorname: { type: String },
  nachname: { type: String },
  geburtsdatum: { type: String },
  strabe: { type: String },
  postleitzahl: { type: String },
  hausnummer: { type: String},
  Ort: { type: String },
  email: { type: String },
  phonenumber: { type: String },
  inputfoto: { type: String },
  profession: { type: String },
  ausgeubterBeruf: { type: String },
  arbeitgeber: { type: String},
  income: { type: String},
  bwaimages: {  type: [String], default: [] },
  employment: { type: String },
  salaryslip: { type: [String],
    default: []
            },
salarySlip1: {  type: [String], default: [] },
salarySlip2: {  type: [String], default: [] },
salarySlip3: {  type: [String], default: [] },
  employcontract: { type: [String], default: [] },
  pets: { type: String },
  einkommensbescheinigungimg:{  type: [String], default: [] },
  rentarea: { type: String },
  proceedings: { type: String },
  apartment: { type: String },
  coverletter: { type: String },
  fläche: { type: String },
  zimerzahl: { type: String },
  imageswbs: { type: [String], default: [] },
  personal: {  type: [String], default: [] },
  idback: {  type: [String], default: [] },
  schufa: {  type: [String], default: [] },
  rentarea: { type: String },
  mietschuldenfreiheit: { type: String },
  mietschuldenfreiheitimg: {  type: [String], default: [] },
  mietverhaltnis: { type: String },
  firstname: { type: String },
  lastname: { type: String },
  email2: { type: String },
  profilephoto: { type: String },
  pdfPath: { type: String },
  parent: { type: String, default: "0" },
  parentId: { type: String },
  childId: { type: mongoose.Schema.Types.ObjectId, ref: 'ApplicationFile', default: null },
  qrCode: { type: String },
  ApplicationImg :{type:String}
  // Add other fields as needed
},{timestamps: true});

export default mongoose.models.ApplicationFile || mongoose.model('ApplicationFile', ApplicationFileSchema);
